mean.x <- NULL
x <- NULL
n.runs <- 5000
n <- 3
p <- .65
for(i in 1:n.runs) {
  x <- c(x,rbinom(1,n,p))
  mean.x <- c(mean.x,mean(x))
}
postscript("LargeNos.eps",horiz=F)
plot(1:n.runs,mean.x,type="l",xlab="Sample size",ylab="")
abline(h=(n*p),col=4)
text(3000,2.8,"X ~ Bino(3,.65)")
dev.off()

x <- seq(-2,2,.01)
n <- length(x)
postscript("Correlation1.eps",horiz=F)
par(mfrow=c(1,2))
y <- x + rnorm(n,0,.1)
plot(x,y)
abline(0,1,col=4,lwd=2)
text(-.75,1.8,"Estimated")
text(-.75,1.5,paste("correlation = ",round(cor(x,y),3),sep=""))
y <- -x + rnorm(n,0,.1)
plot(x,y)
abline(0,-1,col=4,lwd=2)
text(.75,1.8,"Estimated")
text(.75,1.5,paste("correlation = ",round(cor(x,y),3),sep=""))
dev.off()
postscript("Correlation2.eps",horiz=F)
par(mfrow=c(1,2))
y <- rnorm(n,0,.1)
plot(x,y,ylim=c(-1,1))
abline(0,0,col=4,lwd=2)
text(0,.75,"Estimated")
text(0,.66,paste("correlation = ",round(cor(x,y),3),sep=""))
y <- x^2+rnorm(n,0,.1)
plot(x,y)
lines(x,I(x^2),col=4,lwd=2)
text(0,2.75,"Estimated")
text(0,2.6,paste("correlation = ",round(cor(x,y),3),sep=""))
dev.off()

postscript("CLT1.eps",horiz=F)
n <- 5
p <- .8
par(mfrow=c(2,2))
x <- rbinom(1000*10,n,p)
hist(x,xlab="X",main="Binomial(5,0.8)")
x <- matrix(rbinom(1000*5,n,p),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=5")
x <- matrix(rbinom(1000*50,n,p),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=50")
x <- matrix(rbinom(1000*100,n,p),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=100")
dev.off()

postscript("CLT2.eps",horiz=F)
par(mfrow=c(2,2))
x <- runif(1000*10)
hist(x,xlab="X",main="Uniform(0,1)")
x <- matrix(runif(1000*5),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=5")
x <- matrix(runif(1000*50),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=50")
x <- matrix(runif(1000*500),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=500")
dev.off()

postscript("CLT3.eps",horiz=F)
par(mfrow=c(2,2))
x <- rexp(1000*10)
hist(x,xlab="X",main="Exponential(1)")
x <- matrix(rexp(1000*5),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=5")
x <- matrix(rexp(1000*50),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=50")
x <- matrix(rexp(1000*500),ncol=5)
hist(apply(x,1,mean),xlab="Sample means",main="n=500")
dev.off()

postscript("NormalApproxBino.eps",horiz=F)
par(mfrow=c(2,2))
x <- rbinom(5000,10,.5)
hist(x,xlab="X",main="Binomial(10,0.5)")
x <- rbinom(5000,100,.5)
hist(x,xlab="X",main="Binomial(100,0.5)")
x <- rbinom(5000,10,.1)
hist(x,xlab="X",main="Binomial(10,0.1)")
x <- rbinom(5000,100,.1)
hist(x,xlab="X",main="Binomial(100,0.1)")
dev.off()

postscript("Poisson1.eps",horiz=F)
par(mfrow=c(2,2))
x <- rpois(5000,.25)
hist(x,xlab="X",main="Poisson(0.25)")
x <- rpois(5000,2.5)
hist(x,xlab="X",main="Poisson(2.5)")
x <- rpois(5000,5)
hist(x,xlab="X",main="Poisson(5)")
x <- rpois(5000,25)
hist(x,xlab="X",main="Poisson(25)")
dev.off()

################################
## MLEs

x <- rnorm(50,6,3)
hist(x,main="",xlim=c(-20,50),col=4,prob=T)

z.curve <- dnorm(seq(-3,3,.05))
plot(seq(-3,3,.05),z.curve,type="l")
x.range <- seq(-20,50,.1)
z.6.3 <- dnorm(x.range,6,3)
plot(x.range,z.6.3,type="l")
postscript("MLE-R-1.eps",horiz=F)
hist(x,main="",xlim=c(-20,50),col=4,prob=T,ylim=c(0,.15))
dev.off()
postscript("MLE-R-2.eps",horiz=F)
hist(x,main="",xlim=c(-20,50),col=4,prob=T,ylim=c(0,.15))
z.curve <- dnorm(x.range,-6,3)
lines(x.range,z.curve,lwd=3)
abline(v=-6)
text(-11,.14,quote(mu==-6))
dev.off()
postscript("MLE-R-3.eps",horiz=F)
hist(x,main="",xlim=c(-20,50),col=4,prob=T,ylim=c(0,.15))
z.curve <- dnorm(x.range,-6,3)
lines(x.range,z.curve,lwd=3)
abline(v=-6)
text(-11,.14,quote(mu==-6))
z.curve <- dnorm(x.range,12,3)
lines(x.range,z.curve,lwd=3)
abline(v=12)
text(17,.14,quote(mu==12))
dev.off()
postscript("MLE-R-4.eps",horiz=F)
hist(x,main="",xlim=c(-20,50),col=4,prob=T,ylim=c(0,.15))
z.curve <- dnorm(x.range,-6,3)
lines(x.range,z.curve,lwd=3)
abline(v=-6)
text(-11,.14,quote(mu==-6))
z.curve <- dnorm(x.range,12,3)
lines(x.range,z.curve,lwd=3)
abline(v=12)
text(17,.14,quote(mu==12))
x.bar <- mean(x)
z.curve <- dnorm(x.range,x.bar,3)
lines(x.range,z.curve,lwd=3,col=2)
abline(v=x.bar,col=2)
text(2,.15,quote(mu==bar(x)),col=2)
dev.off()


x.range <- seq(-5,160,.1)
z.curve1 <- dnorm(x.range,1,1)
z.curve2 <- dnorm(x.range,100,13)
plot(x.range,z.curve1,type="n",xlab="",ylab="Density",ylim=c(0,.42))
lines(x.range[x.range<45],z.curve1[x.range<45],lwd=3)
abline(v=2.31)
lines(x.range[x.range>45],z.curve2[x.range>45],lwd=3,col=4)
abline(v=130,col=4)
