language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH
    - secure: "dpBGu8eMvtu24fhqc0Qx6fgHDpMx7aZMAZC4uqNlI/q/ZT8vXkX/hZJ5WgVlK7ijiHfsZTDEOB9N7+xwiZ0xKOTJ+kuHLz+BMmi5x8QF0I516+3/FzPi601Pm17+2KvN7SLZBNOzIPI4VOfBFOB2uOjHPzlF7ZQyU+w0C9WNaadXsUK3v265SPo7Zy9MXOihfyjTnynd+zmVhp9nzNFjzDrfcAEblAbFEMRJtDZ5VPPujU9oMRRlrtZw1j/+SlOKUx4LU86ZPBMipnDXtL2od4k/4SpJi9uTxXSPLCtgp3LZzZyV6c9e0mPFnFGj2cw/VK0jwTRtER7alr4DyXhmWStT7qS1kFXhDNf04y8QK7LDAlNr8DNWqoc9DRKLFz6ahrI+kKmGgoGGRVRDhBcxUlL12K/fOBvl+B/ek/iv9lDh3TsWNuihhClt1f1Xm7VTPPHTcJkcE0s1jEd7VekIJMVuiHwRyjV8/8b9WaI98ObJk9/TK35JXEl/J/pgNNKz7Y1ZicdYQhQDvrdh2qfoqm3/vr2McB/N5zSGizsG97Yw4Q/96N/WvQlqMfejbuOd71Lq9yPFywIwsNRpvX/I7AhgnvtSA9sbYIMUhzFZq8DosvgFFAOhcbVOanG3P5nKjYx7Zmp9NnJk5bTjB9JKChwTlV7U2ZKU7E1A0Fq4PCQ="
    
r_github_packages:
  - rstudio/bookdown


#before_install:
#- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full

install:
  - Rscript -e "if (!require('pacman')) install.packages('pacman')"
  - Rscript -e "pacman::p_load(data.table)"
  - Rscript -e "pacman::p_load(bookdown)"
  - Rscript -e "pacman::p_load(formatR)"
  - Rscript -e "pacman::p_load(tidyverse)"



before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
