asym <- read.table("Asym2.txt",header=F)
names(asym) <- c("left","right","varLR","tx")
attach(asym)
col1 <- table(cut(left[tx==0],seq(20.75,25.5,.25)))
col2 <- round(as.numeric(col1*100/sum(col1)),2)
cbind(col1,col2)

summary(left[tx==0])
table(left[tx==0])
quantile(left[tx==0],probs=c(.25,.50,.75))

sqrt(sum((left[tx==0]-mean(left[tx==0]))^2)/29)
sd(left[tx==0])

col1 <- table(cut(left[tx==0],seq(20.5,25.5,.5)))
col2 <- round(as.numeric(col1*100/sum(col1)),2)
cbind(col1,col2)
hist(left[tx==0],breaks=seq(20.5,25.5,.5),col=3,xlab="Left leg length -- controls",main="")

postscript("BirdData1a.eps",horiz=F)
par(mfrow=c(2,2))
hist(left[tx==0],breaks=seq(20.5,25.5,.25),col=3,xlab="Left leg length -- controls",main="")
hist(left[tx==0],breaks=seq(20.5,25.5,.5),col=3,xlab="Left leg length -- controls",main="")
hist(left[tx==0],breaks=seq(20,26,1),col=3,xlab="Left leg length -- controls",main="")
hist(left[tx==0],breaks=seq(20,26,2),col=3,xlab="Left leg length -- controls",main="")
dev.off()

col1 <- table(cut(left[tx==0],seq(20,26,1)))
col2 <- round(as.numeric(col1*100/sum(col1)),2)
cbind(col1,col2)

plot(rep(1,length(left[tx==0])),left[tx==0],
          xlab="",ylab="Left leg length -- controls",main="",axes=F)
axis(2) 

stem(left[tx==0])

boxplot(left[tx==0],ylab="Left leg length -- controls",col=3)
boxplot(c(left[tx==0],right[tx==0])~c(rep(0,length(left[tx==0])),rep(1,length(left[tx==0]))),ylab="Leg length -- controls",names=c("Left","Right"),xlab="Side",col=c(3,4))

LLC.dens <- density(left[tx==0])
LLC.dens$x[LLC.dens$y==max(LLC.dens$y)]
plot(LLC.dens$x,LLC.dens$y,type="l",lwd=3,xlab="Leg Length",ylab="Proportion")
plot(LLC.dens$x,cumsum(LLC.dens$y)/sum(LLC.dens$y),type="l",lwd=3,xlab="Leg Length",ylab="Cumulative distribution")

postscript("BirdData4a.eps",horiz=F)
par(mfrow=c(2,2))
LLC.dens <- density(left[tx==0],bw=.25)
plot(LLC.dens$x,LLC.dens$y,type="l",lwd=3,xlab="Leg Length",ylab="Proportion",main="bw=0.25")
LLC.dens <- density(left[tx==0],bw=.5)
plot(LLC.dens$x,LLC.dens$y,type="l",lwd=3,xlab="Leg Length",ylab="Proportion",main="bw=0.50")
LLC.dens <- density(left[tx==0])
plot(LLC.dens$x,LLC.dens$y,type="l",lwd=3,xlab="Leg Length",ylab="Proportion",main="Default bw")
LLC.dens <- density(left[tx==0],bw=1)
plot(LLC.dens$x,LLC.dens$y,type="l",lwd=3,xlab="Leg Length",ylab="Proportion",main="bw=1.00")
dev.off()

#####
postscript("densities.eps",horiz=F)
par(mfrow=c(2,2))
x<-rgamma(500,.5,5)
x.dens <- density(x)
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="x",ylab="Proportion")
abline(v=mean(x),col=2,lwd=3)
abline(v=median(x),col=4,lwd=3,lty=3)
abline(v=x.dens$x[x.dens$y==max(x.dens$y)],col=3,lwd=3,lty=2)
x<- -rexp(500,3)
x.dens <- density(x)
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="x",ylab="Proportion")
abline(v=mean(x),col=2,lwd=3)
abline(v=median(x),col=4,lwd=3,lty=3)
abline(v=x.dens$x[x.dens$y==max(x.dens$y)],col=3,lwd=3,lty=2)
x<-rnorm(500)
x.dens <- density(x)
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="x",ylab="Proportion")
abline(v=mean(x),col=2,lwd=3)
abline(v=median(x),col=4,lwd=3,lty=3)
abline(v=x.dens$x[x.dens$y==max(x.dens$y)],col=3,lwd=3,lty=2)
x<-c(rnorm(250,0,1),rnorm(250,2.5,.65))
x.dens <- density(x)
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="x",ylab="Proportion")
dev.off()

postscript("transform.eps",horiz=F)
par(mfrow=c(2,2))
x<-rnorm(10000,1,.5)
x.dens <- density(exp(x))
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="x",ylab="Proportion")
abline(v=mean(exp(x)),col=2,lwd=3)
abline(v=median(exp(x)),col=4,lwd=3,lty=3)
x.dens <- density(x)
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="Log x",ylab="Proportion")
abline(v=mean(x),col=2,lwd=3)
abline(v=median(x),col=4,lwd=3,lty=3)
#dev.off()
#postscript("transform.eps",horiz=F)
#par(mfrow=c(1,2))
x<-rgamma(10000,10,4)
x.dens <- density(x)
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="x",ylab="Proportion")
abline(v=mean(x),col=2,lwd=3)
abline(v=median(x),col=4,lwd=3,lty=3)
x.dens <- density(log(x))
plot(x.dens$x,x.dens$y,type="l",lwd=3,xlab="Log x",ylab="Proportion")
abline(v=mean(log(x)),col=2,lwd=3)
abline(v=median(log(x)),col=4,lwd=3,lty=3)
dev.off()



##### Variance example:
x1 <-c(0,0,0,1,1,1,1,4,4)
x2 <-c(0,0,0,2,2,2,2,8,8)
postscript("VarianceEg2.eps",horiz=F)
par(mfrow=c(1,2))
hist(x1,breaks=seq(0,8.5,.5),xlab="Divisor of n",main="")
abline(v=8/3,col=4,lwd=3)
abline(v=mean(x1),col=2,lwd=3,lty=2)
hist(x2,breaks=seq(0,8.5,.5),xlab="Divisor of n-1",main="")
abline(v=8/3,col=4,lwd=3)
abline(v=mean(x2),col=2,lwd=3,lty=2)
dev.off()


##### Normals

postscript("TwoNormals-equalProb.eps",horiz=F)
par(mfrow=c(1,2))
x2 <- rnorm(50000)
dens.x2 <- density(x2)
plot(dens.x2,xlab="",main="",lwd=3)
ploy.xvals <- c(dens.x2$x[length(dens.x2$x)],dens.x2$x[length(dens.x2$x):(length(dens.x2$x)-sum(dens.x2$x>2.31)+1)],dens.x2$x[(length(dens.x2$x)-sum(dens.x2$x>2.31)+1)],dens.x2$x[(length(dens.x2$x)-sum(dens.x2$x>2.31)+1)])
ploy.yvals <- c(0,dens.x2$y[length(dens.x2$x):(length(dens.x2$x)-sum(dens.x2$x>2.31)+1)],dens.x2$y[(length(dens.x2$x)-sum(dens.x2$x>2.31)+1)],0)
polygon(ploy.xvals,ploy.yvals,col=4)
dens.x2 <- density(100+13*x2)
plot(dens.x2,xlab="",main="",lwd=3)
ploy.xvals <- c(dens.x2$x[length(dens.x2$x)],dens.x2$x[length(dens.x2$x):(length(dens.x2$x)-sum(dens.x2$x>130)+1)],dens.x2$x[(length(dens.x2$x)-sum(dens.x2$x>130)+1)],dens.x2$x[(length(dens.x2$x)-sum(dens.x2$x>130)+1)])
ploy.yvals <- c(0,dens.x2$y[length(dens.x2$x):(length(dens.x2$x)-sum(dens.x2$x>130)+1)],dens.x2$y[(length(dens.x2$x)-sum(dens.x2$x>130)+1)],0)
polygon(ploy.xvals,ploy.yvals,col=4)
dev.off()

1-pnorm(2.31)