---
title: Assignment 7 - Inference about a Population Rate ($\lambda$)
subtitle: "Your Name Here and ID number here"
author: "EPIB 607, Fall 2018, McGill University"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: false
    number_sections: true
    toc_depth: 3
    keep_md: false
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
## ---- Setup ------------------------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,          # don't show code
  warning = FALSE,       # don't show warnings
  message = FALSE,       # don't show messages (less serious warnings)
  cache = FALSE,         # set to TRUE to save results from last compilation
  fig.align = "center",   # center figures
  fig.asp = 1,          # fig.aspect ratio
  fig.width = 10        # fig width
)
```


# Cancers near Pickering nuclear station


```{r}
## ---- Question-1 ------------------------------------------------------------
```



# Self-reported percutaneous injuries in interns


```{r}
## ---- Question-2 ------------------------------------------------------------

```



# RCT of HPV vaccine

```{r}
## ---- Question-3 ------------------------------------------------------------

```




# Deaths by Horsekicks in the Prussian Army

```{r}
## ---- Question-4 - --------------------------------------------------------

```




# Crimes on full moon

```{r}
## ---- Question-5 - --------------------------------------------------------

```







# Code {-}

```{r all-code, ref.label=knitr::all_labels(), echo = TRUE, eval = FALSE}

```

